/// Flutter icons CustomIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';

  static const IconData home_filled_rounded = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData wiki = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData chat_checked = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData padong_line = IconData(0xe803, fontFamily: _kFontFam);
  static const IconData padong = IconData(0xe804, fontFamily: _kFontFam);
}
